### ISSUE TITLE
Error when using an instance double from Rspec Mocks

### ISSUE THREAD

**Issue by ryabrody** [local-ch/lhs#212]
Stubbing an instance of `LHS::PhysicalAddress` (which is a child class of `LHS::Record`) with `instance_double` from  `Rspec::Mocks` produces following error:
```ruby
# mock
it 'returns street' do
  let(:physical_address) { instance_double(LCM::PhysicalAddress, street: 'Bahnhofstrasse') }
  expect(physcal_address.street).to eq('Bahnhofstrasse')
end
```
```
# error
RSpec::Mocks::MockExpectationError: the LCM::PhysicalAddress class does not implement the instance method: street
from /Users/francarast/.rvm/gems/ruby-2.2.3/gems/rspec-support-3.4.1/lib/rspec/support.rb:87:in `block in <module:Support>'
```
But the `LHS::Record` does has the instance method street:
```ruby
# rails console
addy = LCM::PhysicalAddress.options(auth: {bearer: '<token>'}).find_by(customer_id: <id>)
[29] pry(main)> addy.street
=>
:name => "Altenburgerstrasse"
:house_no => "7"
```
The `LHS::Record` returns `nil` for any possible method:
```ruby
[30] pry(main)> addy.asdf
=> nil
```
Should an `instance_double` of `LHS::Record` not respond to the methods a `LHS::Records` responds to? 

As "workaround" i am now using `double` instead of `instance_double` but i think it should be also possible to use `instance_double`.

**Comment by spape** [comment]
LHS::Records don't have defined methods for the underlying data. You should not mock expected data (json) by mocking methods, as it's mentioned here: [How to write tests when using lhs](https://github.com/local-ch/lhs#testing-how-to-write-tests-when-using-lhs).
Simply, because they are not methods.

The behavior of LHS::Record returning `nil` is a desired behaviour and tries to lower the risk of exceptions of changing keys in an reactive environment.

**Comment by spape** [comment]
Please reopen again if I missed something here.
